.travis.yml, Cargo.toml, README.md, libmimalloc-sys/build.rs, libmimalloc-sys/src/lib.rs, src/lib.rs
Fix cmake build on windows.
Update to latest mimalloc commit.
Set "MI_OVERRIDE" to "OFF" (no need to build malloc/realloc/... symbols).
Set build target to "mimalloc-static" (no need to build shared or obj targets).
Small README changes.
=> Build on windows + ci enhancements

Cargo.toml, libmimalloc-sys/Cargo.toml, libmimalloc-sys/src/lib.rs, src/lib.rs
=> Removed libc dependency

libmimalloc-sys/src/lib.rs
https://microsoft.github.io/mimalloc/group__extended.html#ga089c859d9eddc5f9b4bd946cd53cebee
cc https://github.com/gnzlbg/mimallocator/pull/5
=> libmimalloc-sys: expose mi_usable_size

libmimalloc-sys/build.rs
This should also fix out_dir for MinSizeRel.
=> fix #18: release Debug build fail on windows

Cargo.toml, libmimalloc-sys/Cargo.toml, libmimalloc-sys/build.rs
I have found it very useful to set `MI_OVERRIDE=ON` when C/C++ code is used by Rust applications/libraries. This PR adds a feature to optionally enable this flag (default is false)
=> Optionally compile override feature.

.github/workflows/ci.yml, libmimalloc-sys/build.rs, src/lib.rs
This:
1. Fixes the CI warnings that I see in #29 
2. Upgrade clippy's warnings to errors. (I'm assuming this is what you wanted, and it's just a bug that you don't have it set up that way, but I'm totally happy to undo this if you'd rather keep clippy as warning-only).
3. Run CI on a schedule so that if Rust updates and causes e.g. clippy or rustfmt problems, you get a notice.
Number 3 means if it starts failing, you get emails until it's fixed, but this avoids forcing contributors to touch/fix parts unrelated to their contribution, or having a busted master. (Personally, this has worked well for me, but maybe if you had a lot of crates it could start being a problem). All that said, I would not fault you if you don't more emails in your life.
Edit: Embarrassingly forgot to rename the PR …
=> Fix clippy, improve CI

libmimalloc-sys/src/lib.rs
This was undefined behavior since the signature was wrong, but in practice it's probably fine, unless someone actually uses the c_void.
At least, on ABIs I'm familiar with that's true, and it's hard to imagine ones where a u8 (what [c_void boils down to](https://doc.rust-lang.org/src/core/ffi.rs.html#35)) isn't returned by register.
Also it was unsafe to call this, anyway -- so callers doing that could be assumed to know better than to use the returned `c_void` for anything.
Fixes #26
=> Don't return a c_void by value from mi_free

libmimalloc-sys/Cargo.toml
ensures at most one copy of mimalloc is linked, see https://doc.rust-lang.org/cargo/reference/manifest.html#the-links-field
=> add links directive to libmimalloc-sys crate

.github/workflows/ci.yml, Cargo.toml, libmimalloc-sys/Cargo.toml, libmimalloc-sys/src/extended.rs, libmimalloc-sys/src/lib.rs, libmimalloc-sys/sys-test/Cargo.toml, libmimalloc-sys/sys-test/build.rs, libmimalloc-sys/sys-test/src/main.rs
Fixes #31. Comes with tests, more CI, and docs.
This goes on top of #30 since it improves the CI. It also includes the fix for #29 which is a one-liner and is required to make the tests pass. 
Once #30 that lands I'll rebase and the commits from it should go away, and if you like the look at this I can close #29 and just let it get subsumed.
This splits stuff into an "extended" API (activated by a feature) and a default API. This is a bit odd, since it's not really on a good/deliberate boundary.
I think perhaps a better boundary would be:
- The minimal API is just the things needed by the `mimalloc::Mimalloc` implementation
- The extended API is everything else.
As it is it's kind of weird that it includes `mi_zalloc` or `mi_usable_size` in the "core", but `mi_calloc` is part of the …
=> Expose most of mimalloc API from libmimalloc-sys

Cargo.toml, libmimalloc-sys/Cargo.toml, libmimalloc-sys/build.rs
Hello,
We are experiencing `cannot allocate memory in static TLS block` error when trying to `dlopen` shared libraries built with mimalloc, same thing is happening with jemallocator but we can solve it by `disable_initial_exec_tls` [feature flag](https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/README.md#cargo-features).
For more information see: https://github.com/microsoft/mimalloc/issues/147
This pull request adds new feature flag with name consistent with cmake build flag, `local_dynamic_tls`.
=> Introduce local_dynamic_tls feature

libmimalloc-sys/build.rs, libmimalloc-sys/src/extended.rs
Although, experimental options are unstable settings within `mimalloc`. Some users may want to try and set those options at runtime.
For example: long running application may want to set `reset_page_delay` options for less frequent purge memory pages to OS
=> NO-ISSUE Expose extended experimental options

libmimalloc-sys/build.rs, libmimalloc-sys/src/extended.rs
This PR address several issues:
- Outdated mi_options
- Turning off unused cmake target (shared lib, tests)
- Remove `-static` flag which forces linking to `static version of libc`. This behavior is not recommended and causes failure build on various env
=> Update extended options, fix build

README.md, libmimalloc-sys/Cargo.toml, libmimalloc-sys/build.rs
This PR replaces the usage of cmake with just straight usage of cc. It replicates some of the logic in the cmakelists but is simplified since this crate only builds a static lib.
Resolves: #51
=> Replace cmake with cc

src/lib.rs
Most important change:
This fixes a soundness bug in the realloc impl, where we were testing versus `layout.size()` and not `new_size`, which will return the wrong results. This probably can cause code to get alignments different than they requested, but maybe nobody noticed, or maybe it's rare enough not to happen much.
Other changes:
- Uses the right alignment constant for mimalloc. (The libstd list had gotten stale anyway)
- Improved logic for when to use the non-`_aligned` version of the apis, based on author recommendation (and a little bit of sanity checking added to it in debug mode).
- Got rid of some extra checks we were doing on macos, which AFAICT was just copied from libstd's sytem GlobalAlloc.
We don't need it because the libstd one was working around a bug in the macos …
=> Improve our GlobalAlloc impl

libmimalloc-sys/src/lib.rs
The `mimalloc_ruust` library is marked as `#![no_std]`, yet `libmimalloc-sys` is not marked as `#![no_std]` so `no_std` users of `mimalloc_rust` will pull in the `std` library as a result. This seems like a small oversight.
My specific use-case for this change is because I wish to create a library that does not link to `std` for a smaller size, but that still requires allocations.
I did not thoroughly check if this will adversely affect other end users, I'm hoping CI/CD will catch these.
=> Mark `libmimalloc_sys` as `no_std` to support `no_std` users.

.github/workflows/ci.yml, libmimalloc-sys/src/extended.rs, libmimalloc-sys/sys-test/Cargo.toml, libmimalloc-sys/sys-test/build.rs
Fixed CI by updating extended.rs.
Also made sure the correct checks are done during the workflow.
Added a run of `libmimalloc-sys-test` for both secure and no secure.
=> Fix CI and update extended.rs

src/lib.rs
Fixes #87 
Fixes #96 
I was able to replicate and fix the test case from https://github.com/purpleprotocol/mimalloc_rust/issues/87#issuecomment-1690419508. However, I wasn't able to replicate the problem from https://github.com/purpleprotocol/mimalloc_rust/issues/96#issue-1778121788, as I don't know the exact versions of the dependencies used. The issue seems related though (secure mode, misaligned allocations) and the alternative crate seems to just use `mi_aligned_alloc` for everything as well.
=> Remove `may_use_unaligned_api`

.github/workflows/ci.yml
[The `actions-rs` actions seem unmaintained.](https://github.com/actions-rs/toolchain/issues/216) I have removed all of them and replaced them with https://github.com/dtolnay/rust-toolchain, which seems like the most popular alternative.
I have also updated all of the actions/checkout actions from v3 to v4.
I also noticed that the `secure` feature was not being tested, so I fixed that issue.
I can split these up into separate PRs if requested.
=> Remove `actions-rs`

libmimalloc-sys/src/extended.rs, libmimalloc-sys/src/lib.rs
mi_usable_size was gated behind the extended feature in https://github.com/purpleprotocol/mimalloc_rust/commit/310ffbef61e6647e134b849a5616475ad7475c98#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759
but one test, `it_calculates_usable_size` was left behind in `lib.rs`.
Move it to `extended.rs` as well.
=> Fix mi_usable_size gating

libmimalloc-sys/build.rs
The `dylib` addition breaks static binaries causing them not never be static again, because the atomic lib is always added as a dynamic library.
Removing the `dylib` should not be an issue, since the compiler will either add it dynamically or statically based upon the compiler settings.
=> Remove `dylib` from atomic linking

libmimalloc-sys/build.rs
For some scenarios, we use `atomic_opt` or `clangrt_builtins` instead of `atomic`.
Related issue: 
https://github.com/sfackler/rust-openssl/pull/2239/files
https://gitee.com/openharmony/third_party_llvm-project/issues/I8MAPC
=> feat: use env to adapt to more general scenarios for atomic

libmimalloc-sys/build.rs
When building with mimalloc as the allocator targeting musl in release mode, the compiler fails due to -Werror=date-time warnings caused by mimalloc's use of __DATE__ and __TIME__ macros. This conflicts with musl's reproducible builds requirements.
This commit adds the -Wno-error=date-time flag to the build configuration to downgrade these specific warnings from errors to warnings. This allows successful compilation while maintaining the functionality of mimalloc.
The change affects only musl targets in release mode and does not alter behavior for other targets or build profiles.
Fixes compilation error: expansion of date/time macro in mimalloc with musl + release combination.
=> Fix mimalloc build failure with musl and release mode
